<?php
/**
 * @var \SM\Customer\Block\Index $block
 */
$customer = $block->getListCustomers();
?>

<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Email</th>
        <th>Store Id</th>
        <th>First Name</th>
        <th>Last Name</th>
    </tr>
    <?php foreach ($customer as $item): ?>
        <tr>
            <td><?= $item['entity_id']; ?></td>
            <td><?= $item['email']; ?></td>
            <td><?= $item['store_id']; ?></td>
            <td><?= $item['firstname']; ?></td>
            <td><?= $item['lastname']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>

